version: "3.7"
services:
  plastrond:
    image: docker.lib.umd.edu/plastrond:latest
    environment:
      - JWT_SECRET
    configs:
      - source: plastrond
        target: /etc/plastrond.yml
      - source: archelon_id
        target: /etc/plastron/auth/archelon_id
        mode: 0400
    volumes:
      - plastrond-jobs:/var/opt/plastron/jobs
      - plastrond-messages:/var/opt/plastron/msg
    ports:
      - 5000:5000
configs:
  archelon_id:
    # Private key for archelon SFTP
    # The corresponding public key should be added to Archelon
    file: ./plastron/archelon_id
  plastrond:
    file: ./plastron/plastron.yml
volumes:
  plastrond-jobs:
  plastrond-messages:
