version: "3.7"
services:
  postgres:
    image: docker.lib.umd.edu/fcrepo-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  activemq:
    image: docker.lib.umd.edu/fcrepo-activemq
    volumes:
      - activemq-data:/var/opt/activemq
    ports:
      - 61616:61616
      - 61613:61613
      - 8161:8161
  solr-fedora4:
    image: docker.lib.umd.edu/fcrepo-solr-fedora4
    volumes:
      - solr-fedora4-data:/var/opt/solr
    ports:
      - 8983:8983
  fuseki:
    image: docker.lib.umd.edu/fcrepo-fuseki
    volumes:
      - fuseki-data:/var/opt/fuseki
    ports:
      - 3030:3030
  repository:
    image: docker.lib.umd.edu/umd-fcrepo-webapp
    configs:
      - source: ip-mapping.properties
        target: /etc/fcrepo/ip-mapping.properties
    volumes:
      - repository-data:/var/umd-fcrepo-webapp
    ports:
      - 8080:8080
    environment:
      - ACTIVEMQ_URL=tcp://activemq:61616
      - CAS_URL_PREFIX=https://shib.idm.umd.edu/shibboleth-idp/profile/cas
      - FCREPO_BASE_URL=http://localhost:8080/
      - IP_MAPPING_FILE=/etc/fcrepo/ip-mapping.properties
      - JWT_SECRET
      - LDAP_URL=ldap://directory.umd.edu
      - LDAP_BASE_DN=ou=people,dc=umd,dc=edu
      - LDAP_BIND_DN=uid=libr-fedora,cn=auth,ou=ldap,dc=umd,dc=edu
      - LDAP_BIND_PASSWORD
      - LDAP_MEMBER_ATTRIBUTE=memberOf
      - LDAP_ADMIN_GROUP=cn=Application_Roles:Libraries:FCREPO:FCREPO-Administrator,ou=grouper,ou=group,dc=umd,dc=edu
      - LDAP_USER_GROUP=cn=Application_Roles:Libraries:FCREPO:FCREPO-User,ou=grouper,ou=group,dc=umd,dc=edu
      - MODESHAPE_DB_DRIVER=org.postgresql.Driver
      - MODESHAPE_DB_URL=jdbc:postgresql://postgres:5432/fcrepo_modeshape5
      - MODESHAPE_DB_USERNAME=fcrepo
      - MODESHAPE_DB_PASSWORD

configs:
  ip-mapping.properties:
    file: ./repository/ip-mapping.properties
volumes:
  postgres-data:
  activemq-data:
  solr-fedora4-data:
  fuseki-data:
  repository-data:
